name: Release new version to Brew

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  release:
    name: Release new version to homebrew/cask
    runs-on: macos-latest

    steps:
      - name: Install Brew and then GH
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && brew install gh


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        run: |
          # if tag starts with v, remove it
          if [[ $(git describe --tags --abbrev=0) == v* ]]; then
            echo TAG=$(git describe --tags --abbrev=0| grep -o -E '[0-9.]+') >> $GITHUB_ENV
          else
            echo TAG=$(git describe --tags --abbrev=0) >> $GITHUB_ENV
          fi

      - name: Add PAT to session
        run: |
          echo 'export HOMEBREW_GITHUB_API_TOKEN=${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}'
          echo 'export HOMEBREW_GITHUB_API_TOKEN=${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}' >> $GITHUB_ENV
          echo 'export HOMEBREW_GITHUB_API_TOKEN=${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}' >> /Users/runner/.bash_profile
          echo ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }} | gh auth login --with-token

      - name: Bump cask
        run: brew bump-cask-pr jamie --version ${{ env.TAG }}
