name: Release new version to Brew

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  release:
    name: Release new version to homebrew/cask
    runs-on: macos-latest

    steps:
      - name: Install Brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        run: echo TAG=$(git describe --tags --abbrev=0| grep -o -E '[0-9.]+') >> $GITHUB_ENV

      - name: Add PAT to session
        run: echo 'export HOMEBREW_GITHUB_API_TOKEN=${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}' >> /Users/runner/.bash_profile

      - name: Bump cask
        run: brew bump-cask-pr jamie --version ${{ env.TAG }}
